[project]
name = "thought-virus"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "accelerate>=1.12.0",
    "ipykernel>=7.1.0",
    "torch>=2.9.1",
    "transformers>=4.57.3",
]
